NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GD4DBFYMYZDQYD6KK5XLPS7VIRXDEJV73KAMPGUNPEJVSIDUKD4XJ3S5",
"GDJ5ESBPG7WLR7F4FVS7ILI2S34HBB5CUADXKYEE57XTIBLN36NMOBHG",
]
VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="Goodness"
ORG_DBA="Goodness DBA"
ORG_URL="https://github.com/guudc"
ORG_LOGO=""
ORG_DESCRIPTION="Guudc stellar asset"
ORG_PHYSICAL_ADDRESS=""
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER="08146634078"
ORG_TWITTER="@Goudnexx"
ORG_GITHUB="github.com/guudc"
ORG_OFFICIAL_EMAIL="goodcsmart@gmail.com"

[[PRINCIPALS]]
name="Amadasun Efosa Goodness"
email="goodcsmart@gmail.com"
twitter="@Goudnexx"
github="github.com/guudc"

[[CURRENCIES]]
code="GUUDC"
issuer="GD4DBFYMYZDQYD6KK5XLPS7VIRXDEJV73KAMPGUNPEJVSIDUKD4XJ3S5"



